---
abstract: 'DebugScreen with detach!'
author:
  - 'Tokuhiro Matsuno <tokuhirom@gmail.com>'
build_requires:
  IO::Scalar: 0
  Test::More: 0
  YAML: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: CGI-ExceptionManager
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.8.0
version: 0.05
